

GET http://localhost:8080/graphql/schema

###
GRAPHQL http://localhost:8080/graphql

{
    getAllCustomers {
        id
        name
        greeting
    }
}


###
GRAPHQL http://localhost:8080/graphql

query  {
    getAllCards {
        account {
            accountType
        }
    }
}


###
GRAPHQL http://localhost:8080/graphql

query{
    getAllCards {
        id
        cardHolder
        account{
            id
            ownerId
            balance
        }
    }
}


###
GRAPHQL http://localhost:8080/graphql

query{
    getAllCustomers {
        id
        name
    }
}

###
GRAPHQL http://localhost:8080/graphql

query{
    getCustomer(id: 2) {
        id
        name
    }
}

###
GRAPHQL http://localhost:8080/graphql

mutation {
    createCustomer(input: { name: "Alice" }) {
        id
        name
    }
}

###
GRAPHQL http://localhost:8080/graphql

mutation {
    createAccount(input: { ownerId: 1, accountType: CURRENT, balance: 500.0 }) {
        id
        ownerId
        accountType
        balance
    }
}

###
GRAPHQL http://localhost:8080/graphql

mutation {
    createCard(input: { cardHolderId: 1, accountId: 1, cardType: PHYSICAL }) {
        id
        cardHolderId
        cardType
        accountId
    }
}

###
GRAPHQL http://localhost:8080/graphql

mutation {
    createCustomerAccountCard(input: {
        customer: { name: "Bob" }
        account: { accountType: CREDIT, balance: 1000.0 }
        card: { cardType: VIRTUAL }
    }) {
        customer { id name }
        account { id ownerId accountType balance }
        card { id cardHolderId accountId cardType }
        errors { message path }
    }
}