
enum CardType {
    VIRTUAL
    PHYSICAL
}

enum AccountType {
    CURRENT
    CREDIT
}

type Card @key(fields: "id"){
    id: ID!
    cardHolderId: ID!
    cardType: CardType!
    accountId: ID!
    account: Account
}


type Account @key(fields: "id"){
    id: ID!
    accountType: AccountType!
    ownerId: ID!
    balance: Float!
}

type Customer{
    id: ID!
    name: String!
    # See GraphQlConfiguration for how greeting is resolved via manual wiring
    greeting: String
}


type Query{
    getAllCards: [Card]
    getCard(id: ID!): Card
    getCards(cardHolder: String!): [Card]

    getAllAccounts: [Account]
    getAccount(id: ID, owner: String): Account

    getAllCustomers: [Customer]
    getCustomer(id: ID): Customer
}