
enum CardType {
    VIRTUAL
    PHYSICAL
}

enum AccountType {
    CURRENT
    CREDIT
}

type Card @key(fields: "id"){
    id: ID!
    cardHolderId: ID!
    cardType: CardType!
    accountId: ID!
    account: Account
}


type Account @key(fields: "id"){
    id: ID!
    accountType: AccountType!
    ownerId: ID!
    balance: Float!
}

type Customer{
    id: ID!
    name: String!
    # See GraphQlConfiguration for how greeting is resolved via manual wiring
    greeting: String
}


type Query{
    getAllCards: [Card]
    getCard(id: ID!): Card
    getCards(cardHolder: String!): [Card]

    getAllAccounts: [Account]
    getAccount(id: ID, owner: String): Account

    getAllCustomers: [Customer]
    getCustomer(id: ID): Customer
}

input CreateCustomerInput {
    name: String!
}

input CreateAccountInput {
    ownerId: ID
    accountType: AccountType!
    balance: Float!
}

input CreateCardInput {
    cardHolderId: ID
    accountId: ID
    cardType: CardType!
}

input CreateCustomerAccountCardInput {
    customer: CreateCustomerInput
    account: CreateAccountInput
    card: CreateCardInput
}

type UserError {
    message: String!
    path: [String!]
}

type CreateCustomerAccountCardPayload {
    customer: Customer
    account: Account
    card: Card
    errors: [UserError!]!
}

type DeleteCardPayload {
    deletedCard: Card
    errors: [UserError!]!
}

type Mutation {
    createCustomer(input: CreateCustomerInput!): Customer!
    createAccount(input: CreateAccountInput!): Account!
    createCard(input: CreateCardInput!): Card!
    createCustomerAccountCard(input: CreateCustomerAccountCardInput!): CreateCustomerAccountCardPayload!
    deleteCard(id: ID!): DeleteCardPayload!
}